# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

resources:
 repositories:
   - repository: java-hello-world-with-maven
     endpoint: azure902
     name: azure902/java-hello-world-with-maven
     ref: master
     

pool:
  vmImage: ubuntu-latest

parameters:
  - name: RepoName
    displayName: Select Repo
    type: string
    default: A
    values:
      - A
      - B

variables:
 - name: RepoName
   value: ${{ parameters.RepoName}}

steps:
- checkout: self
  condition: eq(variables.RepoName, 'A')

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  condition: eq(variables.RepoName, 'A')